name: docker lint
on:
  pull_request:
    branches:
      - 'main'

jobs:
  base-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo "triggered by ${{ github.event_name }}"
      - run: echo "branch ${{ github.ref }}"
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "linting"
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile


